#!/bin/bash

# Entertain Kids on a Dime
open https://www.facebook.com/groups/entertainkidsonadime/search/?query=princess&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D

open https://www.facebook.com/groups/entertainkidsonadime/search/?query=birthday&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D

open https://www.facebook.com/groups/entertainkidsonadime/search/?query=elsa&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D

open https://www.facebook.com/groups/entertainkidsonadime/search/?query=moana&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D

open https://www.facebook.com/groups/entertainkidsonadime/search/?query=belle&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D

open https://www.facebook.com/groups/entertainkidsonadime/search/?query=cinderella&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D

open https://www.facebook.com/groups/entertainkidsonadime/search/?query=ariel&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D

open https://www.facebook.com/groups/entertainkidsonadime/search/?query=rapunzel&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D

open https://www.facebook.com/groups/entertainkidsonadime/search/?query=entertain&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D

open https://www.facebook.com/groups/entertainkidsonadime/search/?query=party&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D

# Pink and Blue:
open https://www.facebook.com/groups/pinkandbluelove/search/?query=princess&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D

open https://www.facebook.com/groups/pinkandbluelove/search/?query=birthday&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D

open https://www.facebook.com/groups/pinkandbluelove/search/?query=elsa&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D

open https://www.facebook.com/groups/pinkandbluelove/search/?query=moana&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D

open https://www.facebook.com/groups/pinkandbluelove/search/?query=belle&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D

open https://www.facebook.com/groups/pinkandbluelove/search/?query=cinderella&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D

open https://www.facebook.com/groups/pinkandbluelove/search/?query=ariel&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D

open https://www.facebook.com/groups/pinkandbluelove/search/?query=rapunzel&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D

open https://www.facebook.com/groups/pinkandbluelove/search/?query=entertain&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D

open https://www.facebook.com/groups/pinkandbluelove/search/?query=party&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D

# Today's Mom:
open https://www.facebook.com/groups/todaysmom2015/search/?query=princess&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D 

open https://www.facebook.com/groups/todaysmom2015/search/?query=birthday&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D 
open https://www.facebook.com/groups/todaysmom2015/search/?query=elsa&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D 
open https://www.facebook.com/groups/todaysmom2015/search/?query=moana&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D 
open https://www.facebook.com/groups/todaysmom2015/search/?query=belle&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D 
open https://www.facebook.com/groups/todaysmom2015/search/?query=cinderella&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D 
open https://www.facebook.com/groups/todaysmom2015/search/?query=ariel&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D 
open https://www.facebook.com/groups/todaysmom2015/search/?query=rapunzel&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D 
open https://www.facebook.com/groups/todaysmom2015/search/?query=entertain&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D 
open https://www.facebook.com/groups/todaysmom2015/search/?query=party&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D 

# Momming Inc.
open https://www.facebook.com/groups/mammamiaworld/search/?query=princess&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D

open https://www.facebook.com/groups/mammamiaworld/search/?query=birthday&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D
open https://www.facebook.com/groups/mammamiaworld/search/?query=elsa&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D
open https://www.facebook.com/groups/mammamiaworld/search/?query=moana&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D
open https://www.facebook.com/groups/mammamiaworld/search/?query=belle&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D
open https://www.facebook.com/groups/mammamiaworld/search/?query=cinderella&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D
open https://www.facebook.com/groups/mammamiaworld/search/?query=ariel&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D
open https://www.facebook.com/groups/mammamiaworld/search/?query=rapunzel&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D
open https://www.facebook.com/groups/mammamiaworld/search/?query=entertain&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D
open https://www.facebook.com/groups/mammamiaworld/search/?query=party&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D

# Vaughan Moms Community:
open https://www.facebook.com/groups/vaughanmoms/search/?query=princess&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D

open https://www.facebook.com/groups/vaughanmoms/search/?query=birthday&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D
open https://www.facebook.com/groups/vaughanmoms/search/?query=elsa&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D
open https://www.facebook.com/groups/vaughanmoms/search/?query=moana&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D
open https://www.facebook.com/groups/vaughanmoms/search/?query=belle&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D
open https://www.facebook.com/groups/vaughanmoms/search/?query=cinderella&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D
open https://www.facebook.com/groups/vaughanmoms/search/?query=ariel&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D
open https://www.facebook.com/groups/vaughanmoms/search/?query=rapunzel&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D
open https://www.facebook.com/groups/vaughanmoms/search/?query=entertain&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D
open https://www.facebook.com/groups/vaughanmoms/search/?query=party&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D

# Mommunity:
open https://www.facebook.com/groups/TheMommunity/search/?query=princess&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D

open https://www.facebook.com/groups/TheMommunity/search/?query=birthday&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D
open https://www.facebook.com/groups/TheMommunity/search/?query=elsa&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D
open https://www.facebook.com/groups/TheMommunity/search/?query=moana&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D
open https://www.facebook.com/groups/TheMommunity/search/?query=belle&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D
open https://www.facebook.com/groups/TheMommunity/search/?query=cinderella&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D
open https://www.facebook.com/groups/TheMommunity/search/?query=ariel&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D
open https://www.facebook.com/groups/TheMommunity/search/?query=rapunzel&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D
open https://www.facebook.com/groups/TheMommunity/search/?query=entertain&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D
open https://www.facebook.com/groups/TheMommunity/search/?query=party&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D

# Etobicoke Moms:
open https://www.facebook.com/groups/357568244356285/search/?query=princess&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D

open https://www.facebook.com/groups/357568244356285/search/?query=birthday&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D
open https://www.facebook.com/groups/357568244356285/search/?query=elsa&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D
open https://www.facebook.com/groups/357568244356285/search/?query=moana&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D
open https://www.facebook.com/groups/357568244356285/search/?query=belle&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D
open https://www.facebook.com/groups/357568244356285/search/?query=cinderella&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D
open https://www.facebook.com/groups/357568244356285/search/?query=ariel&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D
open https://www.facebook.com/groups/357568244356285/search/?query=rapunzel&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D
open https://www.facebook.com/groups/357568244356285/search/?query=entertain&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D
open https://www.facebook.com/groups/357568244356285/search/?query=party&filters_rp_chrono_sort=%7B%22name%22%3A%22chronosort%22%2C%22args%22%3A%22%22%7D

